name: Build Go Application

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            output: app.exe
          - os: ubuntu-latest
            output: app
          - os: macos-latest
            output: app
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: |
          mkdir -p ./bin
          go build -v -o ./bin/${{ matrix.output }} ./main.go

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.os }}
          path: ./bin/${{ matrix.output }}
          retention-days: 5
